### ISSUE TITLE
Kodi 19 compatibility

### ISSUE THREAD

**Issue by bernd-wechner** [bartolomesoriano/repo.amber#1]
Kodi 19 is not released yet, but more and more people are using the alpha which is considered stable enough for daily use I'm told. I'm giving it a spin, to be sure. 

Alas Amber fails to install.

Trying to install it from Shins produces:

![image](https://user-images.githubusercontent.com/7296506/84983804-dd97de00-b17c-11ea-9e7c-208cf3bc7162.png)

And then installing the Amber Repo and trying to install it from that produces:

![image](https://user-images.githubusercontent.com/7296506/84983840-f56f6200-b17c-11ea-91d6-b3c306be088a.png)

I'm happy to fork, clone and work on an update for 19, but would benefit from knowing:

1) If a Kodi 19 branch is welcome.
2) If you take PRs from such a branch.

Methinks the Python issue may be easy enough to fix, not sure. But checking in on the responsiveness of this repo first and any desire to see this favourite skin of mine evolve with Kodi 19.

**Comment by bartolomesoriano** [comment]
Please use the Matrix repo for Amber.  That works fine under Matrix. Thanks.  https://github.com/bartolomesoriano/repo.amber.matrix/blob/master/repository.amber.matrix/repository.amber.matrix-1.0.2.zip

**Comment by bartolomesoriano** [comment]
And the Master branch of Amber is also Matrix compatible.

**Comment by bernd-wechner** [comment]
Thanks, that worked. A bit roundabout to get it to work (install the repo, install the skin, select the skin, quit and restart). I discovered in the process that a longstanding bug I've noticed is actually an Amber bug not a Kodi bug. I'll file that against Amber and close this.
