### ISSUE TITLE
Fanart media view only showing home screen background in netflix style

### ISSUE THREAD

**Issue by tapwizard** [bartolomesoriano/repo.amber#2]
Hello, using the latest version of skin I notice that when using the fanart media view (netflix style) when scrolling through movies there is no picture for movie displayed, just the background in main menu. If I switch to fanart (show info) then the panel shows a box with picture for movie highlighted. I have checked all settings with the skin found in kodi repo and they are exactly the same. Thanks.

**Comment by bartolomesoriano** [comment]
@tapwizard , could you please open this issue in the skin's GitHub, not the repo's GitHub? Thanks.
